In [2]:
#!pip install tensorflow_text
#!pip install tensorflow_hub==0.16.1
#!pip install tf-keras
!pip install -U "tensorflow-text==2.15.*"

INFO: pip is looking at multiple versions of tf-keras to determine which version is compatible with other requirements. This could take a while.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 50.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 475.2/475.2 MB 3.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 55.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 58.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 71.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 442.0/442.0 kB 30.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 46.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.9/77.9 kB 5.3 MB/s eta 0:00:00
  Attempting uninstall: wrapt
    Found existing installation: wrapt 1.17.0
    Uninstalling wrapt-1.17.0:
      Successfully uninstalled wrapt-1.17.0
  Attempting uninstall: ml-dtypes
    Found existing installation: ml-dtypes 0.4

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text as text
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [2]:
data=pd.read_excel("AccidentCategoryTrainingData.xlsx")
data.head(10)

content         result
0  While driving home from work, I was rear-ended...  Bodily Injury
1  I was stopped at a red light when a distracted...  Bodily Injury
2  During a heavy rainstorm, I lost control of my...  Bodily Injury
3  While merging onto the highway, another car si...  Bodily Injury
4  I was hit by a car running a red light while I...  Bodily Injury
5  While driving on a rural road, a deer jumped i...  Bodily Injury
6  A car suddenly cut me off on the highway, caus...  Bodily Injury
7  While parked on the side of the road, a truck ...  Bodily Injury
8  I was hit head-on by a drunk driver who crosse...  Bodily Injury
9  While driving in heavy traffic, a car rear-end...  Bodily Injury

In [3]:
data.groupby("result").describe()

content         \
                            count unique   
result                                     
Bodily Injury                  20     19   
Other                          13     13   
Property Damage                20     20   
Uninsured or Underinsured      20     20   

                                                                              \
                                                                         top   
result                                                                         
Bodily Injury              While driving in heavy traffic, a car rear-end...   
Other                      While walking my dog, I slipped on a patch of ...   
Property Damage            While backing out of my driveway, I misjudged ...   
Uninsured or Underinsured  I was driving down the street when suddenly, a...   

                                
                          freq  
result                          
Bodily Injury                2  
Other                        1  
Property Damage              1  
Uninsured or Underinsured    1

In [4]:
le=LabelEncoder()
data["encoded_result"]=le.fit_transform(data["result"])


In [28]:
data.tail(40)


content  \
33  I was driving in a parking lot when I accident...   
34  While pulling into a parking space, I accident...   
35  I was driving down a narrow alley when my side...   
36  While reversing in a parking garage, I acciden...   
37  While attempting to park in a tight space, I a...   
38  I was driving in a construction zone when I ac...   
39  While reversing in my driveway, I accidentally...   
40  I was driving down the street when suddenly, a...   
41  As I approached the intersection, I noticed a ...   
42  While driving on the highway, I encountered an...   
43  I was peacefully driving through the neighborh...   
44  As I was driving home, a car driven by an unin...   
45  While driving on a busy street, I encountered ...   
46  I had just entered the intersection when an un...   
47  While driving through the city, an uninsured p...   
48  As I was driving along the road, an uninsured ...   
49  I was driving on a quiet street when an uninsu...   
50  While driving through an intersection, an unin...   
51  I had just turned onto the highway when an uni...   
52  While driving on a busy road, an uninsured dri...   
53  I was driving down the road when an uninsured ...   
54  As I was driving through the intersection, an ...   
55  I never saw the uninsured pedestrian crossing ...   
56  The uninsured driver lost control of their veh...   
57  I was driving on the highway when an uninsured...   
58  An uninsured driver rear-ended my car while I ...   
59  I was driving through an intersection when an ...   
60  While walking my dog, I slipped on a patch of ...   
61  I was frying some chicken for dinner when the ...   
62  While painting my house, I accidentally knocke...   
63  I was flying my drone in the park when it sudd...   
64  While mowing my lawn, a rock was thrown by the...   
65  I was practicing my golf swing in the backyard...   
66  While cleaning my gutters, I accidentally drop...   
67  I was trimming my tree when a branch fell and ...   
68  While installing a new satellite dish, I accid...   
69  I was using my chainsaw to cut down a tree whe...   
70  While using my leaf blower, I accidentally ble...   
71  I was using my pressure washer to clean my dri...   
72  While using my snow blower, I accidentally ble...   

                       result  encoded_result  
33            Property Damage               2  
34            Property Damage               2  
35            Property Damage               2  
36            Property Damage               2  
37            Property Damage               2  
38            Property Damage               2  
39            Property Damage               2  
40  Uninsured or Underinsured               3  
41  Uninsured or Underinsured               3  
42  Uninsured or Underinsured               3  
43  Uninsured or Underinsured               3  
44  Uninsured or Underinsured               3  
45  Uninsured or Underinsured               3  
46  Uninsured or Underinsured               3  
47  Uninsured or Underinsured               3  
48  Uninsured or Underinsured               3  
49  Uninsured or Underinsured               3  
50  Uninsured or Underinsured               3  
51  Uninsured or Underinsured               3  
52  Uninsured or Underinsured               3  
53  Uninsured or Underinsured               3  
54  Uninsured or Underinsured               3  
55  Uninsured or Underinsured               3  
56  Uninsured or Underinsured               3  
57  Uninsured or Underinsured               3  
58  Uninsured or Underinsured               3  
59  Uninsured or Underinsured               3  
60                      Other               1  
61                      Other               1  
62                      Other               1  
63                      Other               1  
64                      Other               1  
65                      Other               1  
66                      Other               1  
67                      Othe

In [6]:
# Train Test Split

In [7]:
X_train,X_test,y_train,y_test=train_test_split(data["content"],data["encoded_result"],test_size=0.20,random_state=42)

In [8]:
X_train.shape

(58,)

In [9]:
X_test.shape

(15,)

In [ ]:
#Now lets import BERT model and get embeding vectors

In [10]:
bert_preprocess=hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3",name="bert_preprocess")
bert_encoder   =hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4",name="bert_encoder")

In [11]:
#Test
preprocess=bert_preprocess(["Hello World","Nice see you"])
encoder=bert_encoder(preprocess)


In [12]:
#Creation Functions to create embeddings
def get_text_embeddings(text):
  preprocess=bert_preprocess(text)
  encoder   =bert_encoder(preprocess)

  return encoder["pooled_output"]


In [13]:
get_text_embeddings(["Hello World","Nice see you"])

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.90584826, -0.30958164, -0.6152443 , ..., -0.300495  ,
        -0.6393687 ,  0.9164875 ],
       [-0.82861996, -0.2331982 ,  0.270099  , ...,  0.22167043,
        -0.6020718 ,  0.88220173]], dtype=float32)>

In [27]:
# Model building(we can build functional model here.Other type of model is called Sequential Model)

In [14]:
#Input data preprocessing
text_input=tf.keras.layers.Input(shape=(),dtype=tf.string,name='text')
preprocess_output=bert_preprocess(text_input)
encoder_output   =bert_encoder(preprocess_output)

In [16]:
#Neural Network Layers Creation
num_classes=4
InputandDropout_Layer=tf.keras.layers.Dropout(0.1,name="Dropout")(encoder_output["pooled_output"])
output_layer=tf.keras.layers.Dense(num_classes, activation='softmax', name="output")(InputandDropout_Layer)



In [19]:
#Final Model

model=tf.keras.Model(inputs=[text_input],outputs=[output_layer])

In [21]:
model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 text (InputLayer)           [(None,)]                    0         []                            
                                                                                                  
 bert_preprocess (KerasLaye  {'input_type_ids': (None,    0         ['text[0][0]']                
 r)                          128),                                                                
                              'input_mask': (None, 128)                                           
                             , 'input_word_ids': (None,                                           
                              128)}                                                               
                                                                                              

In [22]:
len(X_train)

58

In [23]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [29]:
model.fit(X_train, y_train, epochs=50)

Epoch 1/50
2/2 [==============================] - 30s 13s/step - loss: 1.3348 - accuracy: 0.3103
Epoch 2/50
2/2 [==============================] - 30s 13s/step - loss: 1.3861 - accuracy: 0.3793
Epoch 3/50
2/2 [==============================] - 32s 13s/step - loss: 1.3027 - accuracy: 0.2586
Epoch 4/50
2/2 [==============================] - 31s 13s/step - loss: 1.2960 - accuracy: 0.3621
Epoch 5/50
2/2 [==============================] - 29s 12s/step - loss: 1.1909 - accuracy: 0.5172
Epoch 6/50
2/2 [==============================] - 29s 13s/step - loss: 1.3280 - accuracy: 0.3448
Epoch 7/50
2/2 [==============================] - 30s 13s/step - loss: 1.2744 - accuracy: 0.4138
Epoch 8/50
2/2 [==============================] - 31s 14s/step - loss: 1.2252 - accuracy: 0.4138
Epoch 9/50
2/2 [==============================] - 30s 14s/step - loss: 1.3100 - accuracy: 0.3276
Epoch 10/50
2/2 [==============================] - 30s 13s/step - loss: 1.2055 - accuracy: 0.5172
Epoch 11/50
2/2 [============

In [30]:
model.evaluate(X_test, y_test)

1/1 [==============================] - 8s 8s/step - loss: 0.8843 - accuracy: 0.7333


[0.8843194246292114, 0.7333333492279053]

In [31]:
#Test
reviews = [
          'While riding a motorcycle, I was hit by a speeding car at a junction. The collision resulted in a fractured rib and a sprained ankle. I have been prescribed rest and am attending regular therapy sessions.',
          'I was driving cautiously in a construction zone when I accidentally hit a traffic cone that had been poorly placed. The cone struck a pedestrian sign, knocking it over, while my cars front bumper got scratched'
         ]
model.predict(reviews)

1/1 [==============================] - 1s 970ms/step


array([[0.59537476, 0.06637261, 0.20172898, 0.13652366],
       [0.00975597, 0.38208488, 0.35933322, 0.24882585]], dtype=float32)