In [1]:
### Libraries USed Tensorflow> 2.0  and keras

In [3]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
vocab_size=10000

In [8]:
onehot_repr=[one_hot(words,vocab_size) for words in sent]

In [9]:
onehot_repr

[[7956, 9127, 816, 2517],
 [7956, 9127, 816, 8889],
 [7956, 1744, 816, 1549],
 [6513, 3938, 9991, 4460, 1862],
 [6513, 3938, 9991, 4460, 9836],
 [2827, 7956, 4243, 816, 3646],
 [7172, 5631, 9448, 4460]]

### Word Embadding Representation

In [10]:
from tensorflow.keras.layers import Embedding 
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [11]:
set_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=set_length)

In [12]:
embedded_docs

array([[   0,    0,    0,    0, 7956, 9127,  816, 2517],
       [   0,    0,    0,    0, 7956, 9127,  816, 8889],
       [   0,    0,    0,    0, 7956, 1744,  816, 1549],
       [   0,    0,    0, 6513, 3938, 9991, 4460, 1862],
       [   0,    0,    0, 6513, 3938, 9991, 4460, 9836],
       [   0,    0,    0, 2827, 7956, 4243,  816, 3646],
       [   0,    0,    0,    0, 7172, 5631, 9448, 4460]])

In [13]:
model=Sequential()

In [14]:
model.add(Embedding(vocab_size,10,input_length=set_length))

Instructions for updating:
Colocations handled automatically by placer.


In [15]:
model.compile('adam','mse')

Instructions for updating:
Use tf.cast instead.


In [16]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [17]:
model.predict(embedded_docs)

array([[[-0.03173004, -0.01944615, -0.0211279 ,  0.0313856 ,
          0.02887997, -0.01450024, -0.00787168,  0.02140123,
          0.0340798 ,  0.00115161],
        [-0.03173004, -0.01944615, -0.0211279 ,  0.0313856 ,
          0.02887997, -0.01450024, -0.00787168,  0.02140123,
          0.0340798 ,  0.00115161],
        [-0.03173004, -0.01944615, -0.0211279 ,  0.0313856 ,
          0.02887997, -0.01450024, -0.00787168,  0.02140123,
          0.0340798 ,  0.00115161],
        [-0.03173004, -0.01944615, -0.0211279 ,  0.0313856 ,
          0.02887997, -0.01450024, -0.00787168,  0.02140123,
          0.0340798 ,  0.00115161],
        [-0.0358041 , -0.00591692,  0.01840824, -0.02455699,
          0.01643315,  0.01784236,  0.04914376,  0.0283285 ,
          0.02991403,  0.02088293],
        [-0.02932071,  0.01383418, -0.01975195,  0.01420318,
         -0.04898718, -0.02002957, -0.01568725, -0.0454464 ,
          0.03447261, -0.03836309],
        [ 0.04548723,  0.03865751, -0.03899451,  0.0

In [18]:
embedded_docs[0]

array([   0,    0,    0,    0, 7956, 9127,  816, 2517])

In [20]:
model.predict(embedded_docs)[0]

array([[-0.03173004, -0.01944615, -0.0211279 ,  0.0313856 ,  0.02887997,
        -0.01450024, -0.00787168,  0.02140123,  0.0340798 ,  0.00115161],
       [-0.03173004, -0.01944615, -0.0211279 ,  0.0313856 ,  0.02887997,
        -0.01450024, -0.00787168,  0.02140123,  0.0340798 ,  0.00115161],
       [-0.03173004, -0.01944615, -0.0211279 ,  0.0313856 ,  0.02887997,
        -0.01450024, -0.00787168,  0.02140123,  0.0340798 ,  0.00115161],
       [-0.03173004, -0.01944615, -0.0211279 ,  0.0313856 ,  0.02887997,
        -0.01450024, -0.00787168,  0.02140123,  0.0340798 ,  0.00115161],
       [-0.0358041 , -0.00591692,  0.01840824, -0.02455699,  0.01643315,
         0.01784236,  0.04914376,  0.0283285 ,  0.02991403,  0.02088293],
       [-0.02932071,  0.01383418, -0.01975195,  0.01420318, -0.04898718,
        -0.02002957, -0.01568725, -0.0454464 ,  0.03447261, -0.03836309],
       [ 0.04548723,  0.03865751, -0.03899451,  0.04361422,  0.02021926,
         0.02316976,  0.02654887,  0.03294506